version: '3.8'
services:
  rasa:
    image: rasa/rasa:latest
    ports:
      - "5005:5005"  # Mở cổng mặc định của Rasa
    volumes:
      - ./models:/app/models  # Mount thư mục chứa mô hình
      - ./data:/app/data  # Mount thư mục chứa dữ liệu

  action_server:
    image: rasa/rasa-sdk:latest
    ports:
      - "5055:5055"  # Mở cổng của action server
    volumes:
      - ./actions:/app/actions  # Mount thư mục chứa các action

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"

#  kafka:
#    image: wurstmeister/kafka:latest
#    ports:
#      - "9092:9092"
#    environment:
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9092
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
#      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9092
  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092" # Cổng cho listener OUTSIDE
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092  # Sử dụng cổng 9093 cho INSIDE
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092  # Đảm bảo INSIDE sử dụng cổng 9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE  # Chỉ định listener cho giao tiếp giữa các broker



  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.0.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.0.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
